routes/web.php
<?php

Route::get('/user', 'User\userController@index');



// route for admin
Route::namespace('Admin')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('index.home');
    });
    Route::get('/admin-home', 'AdminController@index')->name('admin.home');
    // pdc
    Route::resource('/admin/PDC', 'pdcController');
    Route::patch('/admin/PDC/dateout/update/{id}', 'pdcController@update_date_out')->name('PDC.date-out.update');
    Route::patch('/admin/PDC/progress_job/update/{id}', 'pdcController@update_progress_job')->name('PDC.progress-job.update');
    Route::patch('/admin/PDC/startprogress/update/{id}', 'pdcController@update_start_progress')->name('PDC.start-progress.update');
    Route::patch('/admin/PDC/done/update/{id}', 'pdcController@update_done')->name('PDC.done.update');


    // mkt
    Route::resource('/admin/MKT', 'mktController');
    Route::patch('/admin/MKT/dateout/update/{id}', 'mktController@update_date_out')->name('MKT.date-out.update');
    Route::patch('/admin/MKT/progress_job/update/{id}', 'mktController@update_progress_job')->name('MKT.progress-job.update');
    Route::patch('/admin/MKT/startprogress/update/{id}', 'mktController@update_start_progress')->name('MKT.start-progress.update');
    Route::patch('/admin/MKT/done/update/{id}', 'mktController@update_done')->name('MKT.done.update');

    // ppc
    Route::resource('/admin/PPC', 'disassyController');
    Route::patch('/admin/PPC/dateout/update/{id}', 'disassyController@update_date_out')->name('PPC.date-out.update');
    Route::patch('/admin/PPC/progress_job/update/{id}', 'disassyController@update_progress_job')->name('PPC.progress-job.update');
    Route::patch('/admin/PPC/startprogress/update/{id}', 'disassyController@update_start_progress')->name('PPC.start-progress.update');
    Route::patch('/admin/PPC/done/update/{id}', 'disassyController@update_done')->name('PPC.done.update');

    //machine
    Route::resource('/admin/machining', 'machineController');
    Route::patch('/admin/machining/startprogress/update/{id}', 'machineController@update_start_progress')->name('machining.start-progress.update');
    Route::patch('/admin/machining/endprogress/update/{id}', 'machineController@update_end_progress')->name('machining.end-progress.update');
    Route::patch('/admin/newmachine', 'machineController@new_machine')->name('machining.new-machine');
    Route::get('/admin/machining/done/{id}','machineController@done')->name('machining.done');
    Route::get('newmachine','machineController@machine_create')->name('machine.create');
    Route::post('machine/store','machineController@machine_store')->name('machine.store');

    //partkit
    Route::resource('/admin/partkit', 'partkitController');

    //partkit_po
    Route::get('/admin/partkit-po/create', 'partkitController@create_po')->name('partkit.create_po');
    Route::post('/admin/partkit-po/store', 'partkitController@store_po')->name('partkit.store_po');
    Route::patch('/admin/partkit-po/actrelease/update/{id}', 'partkitController@update_act_release_po')->name('partkit_po.update.act_release_po');
    Route::patch('/admin/partkit-po/ponumber/update/{id}', 'partkitController@update_po_number')->name('partkit_po.update.po_number');


    //assembly
    Route::resource('/admin/assembly', 'assemblyController');
    Route::patch('/admin/assembly-update/tube/{id}', 'assemblyController@update_tube')->name('assembly.update.tube');
    Route::patch('/admin/assembly-update/rod/{id}', 'assemblyController@update_rod')->name('assembly.update.rod');
    Route::patch('/admin/assembly-update/piston/{id}', 'assemblyController@update_piston')->name('assembly.update.piston');
    Route::patch('/admin/assembly-update/gland/{id}', 'assemblyController@update_gland')->name('assembly.update.gland');
    Route::patch('/admin/assembly-update/midle/{id}', 'assemblyController@update_midle')->name('assembly.update.midle');
    Route::patch('/admin/assembly-update/seal_kit/{id}', 'assemblyController@update_seal_kit')->name('assembly.update.seal_kit');
    Route::patch('/admin/assembly-update/bushing/{id}', 'assemblyController@update_bushing')->name('assembly.update.bushing');
    Route::patch('/admin/assembly-update/part_related/{id}', 'assemblyController@update_part_related')->name('assembly.update.part_related');

    // delay
    Route::resource('admin/delay', 'delayController');
    Route::patch('admin/delay/unpause/{id}', 'delayController@unpause')->name('machining.unpause');

    // routing
    Route::resource('/admin/routing', 'routingController');
    Route::post('/admin/routing/excel', 'routingController@excel')->name('routing.excel');
    Route::get('/admin/routing-edit/pdc', 'routingController@routing_pdc')->name('routing-edit.pdc');
    Route::post('/admin/routing-edit/pdc', 'routingController@routing_pdc_store')->name('routing-store.pdc');
    Route::delete('/admin/routing-edit/pdc/{id}', 'routingController@routing_pdc_delete')->name('relation_routing.destroy.pdc');
    Route::post('/admin/routing-edit/pdcstore', 'routingController@routing_pdc_store')->name('relation_routing.store.pdc');

    // routing ppc
    Route::get('/admin/routing-edit/ppc', 'routingController@routing_ppc')->name('routing-edit.ppc');
    Route::post('/admin/routing-edit/ppc', 'routingController@routing_ppc_store')->name('routing-store.ppc');
    Route::delete('/admin/routing-edit/ppc/{id}', 'routingController@routing_ppc_delete')->name('relation_routing.destroy.ppc');
    Route::post('/admin/routing-edit/ppcstore', 'routingController@routing_ppc_store')->name('relation_routing.store.ppc');

    //routing mkt
    Route::get('/admin/routing-edit/mkt', 'routingController@routing_mkt')->name('routing-edit.mkt');
    Route::post('/admin/routing-edit/mkt', 'routingController@routing_mkt_store')->name('routing-store.mkt');
    Route::delete('/admin/routing-edit/mkt/{id}', 'routingController@routing_mkt_delete')->name('relation_routing.destroy.mkt');
    Route::post('/admin/routing-edit/mktstore', 'routingController@routing_mkt_store')->name('relation_routing.store.mkt');

    // history
    Route::resource('/admin/history', 'historyController');

    // 
    Route::get('/pdc','userController@index')->name('user.pdc');
    Route::get('/station1', function () {
        return view('station1.home');
    });
});


Auth::routes();

app/Http/Controllers/Admin/routingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
// upload excel
use Excel;
use App\Imports\RoutingImport;
// model
use App\Model\routing;
use App\Model\Relation\relation_routings;


class routingController extends Controller
{
    public function index()
    {
        $routings   = routing::all();
        return view('admin.routing.index', compact('routings'));
    }


    public function create()
    {
        return view('admin.routing.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'grup'                 => 'required|',
            'model_unit'           => 'required',
            'komponen'             => 'required',
            'sub_komponen'         => 'required',
            'kategori_kerusakan'   => 'required',
            'activity'             => 'required',
            'estimasi'             => 'required',

        ];

        $customMessages = [
            'required' => 'Kolom :attribute Harus diisi'
        ];

        $this->validate($request, $rules, $customMessages);
        $validatedData = $request->validate([]);

        $routing = new routing;

        $routing->grup                  = $request->grup;
        $routing->model_unit            = $request->model_unit;
        $routing->komponen              = $request->komponen;
        $routing->sub_komponen          = $request->sub_komponen;
        $routing->kategori_kerusakan    = $request->kategori_kerusakan;
        $routing->activity              = $request->activity;
        $routing->estimasi              = $request->estimasi;

        $routing->save();

        return redirect(route('routing.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        $routing = routing::find($id);
        $routing->delete();

        return redirect()->back();
    }

    public function excel(Request $request)
    {

        $this->validate($request, [
            'file'    => 'required|mimes:xls,xlsx,ods',
        ]);

        // menangkap file excel
        $file = $request->file('file');
        // // membuat nama file unik
        // $nama_file = rand() . $file->getClientOriginalName();

        // upload ke folder file_siswa di dalam folder public
        // $file->move('file_routing', $nama_file);

        // import data
        Excel::import(new RoutingImport, $file);

        return redirect(route('routing.index'));
    }

    public function routing_pdc()
    {
        $routings = routing::all();
        $relation_routings = relation_routings::where('table_name', 'pdc')->get();
        return view('admin.pdc.routing-edit', compact('routings', 'relation_routings'));
    }
    public function routing_pdc_delete($id)
    {

        $relation_routings = relation_routings::where('table_name', 'pdc')->get();
        $data = relation_routings::find($id);
        foreach ($relation_routings as $relation_routing) {
            if ($relation_routing->urutan > $data->urutan) {
                $relation_routing_update = relation_routings::find($relation_routing->id);
                $relation_routing_update->urutan = $relation_routing_update->urutan - 1;
                $relation_routing_update->update();
            }
        }
        $data->delete();
        return redirect()->back();
    }

    public function routing_pdc_store(Request $request)
    {
        $relation_routings = relation_routings::where('table_name', 'pdc')->get();
        $routing           = routing::where([
            'model_unit'=>$request->unit_model,
            'komponen'=>$request->komponen,
            'sub_komponen'=>$request->sub_komponen,
            'kategori_kerusakan'=>$request->kategori_kerusakan,
            'activity'=>$request->progress_job,
            ])->get()->first();

        $data = new relation_routings;
        $data->table_name   = 'pdc';
        $data->routing_id   = $routing->id;
        $data->urutan       = count($relation_routings) + 1;
        $data->save();
        return redirect()->back();
    }

    // mkt
    public function routing_mkt()
    {
        $routings = routing::all();
        $relation_routings = relation_routings::where('table_name', 'mkt')->get();
        return view('admin.mkt.routing-edit', compact('routings', 'relation_routings'));
    }
    public function routing_mkt_delete($id)
    {

        $relation_routings = relation_routings::where('table_name', 'mkt')->get();
        $data = relation_routings::find($id);
        foreach ($relation_routings as $relation_routing) {
            if ($relation_routing->urutan > $data->urutan) {
                $relation_routing_update = relation_routings::find($relation_routing->id);
                $relation_routing_update->urutan = $relation_routing_update->urutan - 1;
                $relation_routing_update->update();
            }
        }
        $data->delete();
        return redirect()->back();
    }

    public function routing_mkt_store(Request $request)
    {
        $relation_routings = relation_routings::where('table_name', 'mkt')->get();
        $routing           = routing::where([
            'model_unit'=>$request->unit_model,
            'komponen'=>$request->komponen,
            'sub_komponen'=>$request->sub_komponen,
            'kategori_kerusakan'=>$request->kategori_kerusakan,
            'activity'=>$request->progress_job,
            ])->get()->first();
        $data = new relation_routings;
        $data->table_name   = 'mkt';
        $data->routing_id   = $routing->id;
        $data->urutan       = count($relation_routings) + 1;
        $data->save();
        return redirect()->back();
    }

    // ppc

    public function routing_ppc()
    {
        $routings = routing::all();
        $relation_routings = relation_routings::where('table_name', 'ppc')->get();
        return view('admin.ppc.routing-edit', compact('routings', 'relation_routings'));
    }
    public function routing_ppc_delete($id)
    {

        $relation_routings = relation_routings::where('table_name', 'ppc')->get();
        $data = relation_routings::find($id);
        foreach ($relation_routings as $relation_routing) {
            if ($relation_routing->urutan > $data->urutan) {
                $relation_routing_update = relation_routings::find($relation_routing->id);
                $relation_routing_update->urutan = $relation_routing_update->urutan - 1;
                $relation_routing_update->update();
            }
        }
        $data->delete();
        return redirect()->back();
    }

    public function routing_ppc_store(Request $request)
    {
        $relation_routings = relation_routings::where('table_name', 'ppc')->get();

        $routing           = routing::where([
            'model_unit'=>$request->unit_model,
            'komponen'=>$request->komponen,
            'sub_komponen'=>$request->sub_komponen,
            'kategori_kerusakan'=>$request->kategori_kerusakan,
            'activity'=>$request->progress_job,
            ])->get()->first();
        $data = new relation_routings;
        $data->table_name   = 'ppc';
        $data->routing_id   = $routing->id;
        $data->urutan       = count($relation_routings) + 1;
        $data->save();
        return redirect()->back();
    }
}

resources/views/admin/routing/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Add New Routing</strong>
        <a class="btn btn-warning float-right" href="{{route('routing.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        <hr>
        <form action="{{route('routing.store')}}" method="POST">
            @csrf
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Grup</label>
                            <input type="text" name="grup" class="form-control" placeholder="ex: CYL">
                        </div>
                        <div class="col-md-6">
                            <label>Model Unit</label>
                            <input type="text" name="model_unit" class="form-control" placeholder="ex: PC2000">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Komponen</label>
                            <input type="text" name="komponen" class="form-control" placeholder="ex: Boom">
                        </div>
                        <div class="col-md-6">
                            <label>Sub Komponen</label>
                            <input type="text" name="sub_komponen" class="form-control" placeholder="ex: Gland">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Kategori Kerusakan</label>
                            <input type="text" name="kategori_kerusakan" class="form-control" placeholder="ex: Ringan">
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-12">
                            <label>Activity</label>
                            <textarea name="activity" rows="5" placeholder="ex: Polish Gland" class="form-control"></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Estimasi</label>
                            <input type="number" name="estimasi" class="form-control" placeholder="ex: 4">
                            <label class="text-danger">*hanya isi angka dalam hitungan jam</label>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-success form-control col-md-10">Tambah</button>
        </form>
        <br>
        <hr>
        <br>
        <form action="{{route('routing.excel')}}" method="POST" enctype="multipart/form-data">
            <h4>Tambahkan dengan excel</h4>
            @csrf
            <input type="file" name="file" id="">
            <button type="submit" class="btn btn-success">Tambah dari excel</button>
        </form>

    </div>
</div>
@endsection

resources/views/admin/routing/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <strong class="card-title">Edit Machine Data</strong>
            <a class="btn btn-warning float-right" href="{{route('machine.index')}}">Back</a>
        </div>

        <div class="card-body">
            <form action="{{route('machine.update',$machine->id)}}" method="POST">
                @csrf @method('PATCH')
                <input type="text" name="name" class="form-control" placeholder="Machine Name" value="{{$machine->name}}" >
                <input type="text" name="damage_type" class="form-control" placeholder="Jenis Kerusakan" value="{{$machine->damage_type}}" >
                <input type="date" name="date_in" class="form-control" placeholder="Tanggal Masuk" value="{{$machine->date_in}}" >
                <a href="#" id="button-select-plant" onclick="
                document.getElementById('button-select-plant').style.display=('none');
                document.getElementById('select-plant').style.display=('block');
                ">pilih plant</a>
                <select name="plant_id" id="select-plant" style="display:none">
                    @foreach ($plants as $plant)    
                    <option value="{{$plant->id}}">{{$plant->name}}</option>
                    @endforeach
    
                </select>
                <button type="submit" class="btn btn-success">Update</button>
                <a href="{{route('machine.index')}}" class="btn btn-warning">Kembali</a>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/routing/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Routing Table</strong>
        <a class="btn btn-danger float-right" href="{{route('routing.create')}}">Create New</a>
    </div>

    <div class="card-body">

        <div class="table-stats order-table ov-h">
            <table class="table ">
                <thead>
                    <tr>
                        <th class="serial" style="padding-top:14px;">#</th>
                        <th>Grup</th>
                        <th>Model Unit</th>
                        <th>Komponen</th>
                        <th>Sub Komponen</th>
                        <th>Kat Kerusakan</th>
                        <th>Activity</th>
                        <th>Estimasi LT Prod.</th>
                        <th>Aksi</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach ($routings as $routing)

                    <tr>
                        <td class="serial">{{$loop->index + 1}}</td>
                        <td>{{$routing->grup}}</td>
                        <td>{{$routing->model_unit}}</td>
                        <td>{{$routing->komponen}}</td>
                        <td>{{$routing->sub_komponen}}</td>
                        <td>{{$routing->kategori_kerusakan}}</td>
                        <td>{{$routing->activity}}</td>
                        <td>{{$routing->estimasi}}</td>

                        <td>
                            <a href="{{route('routing.edit',$routing->id)}}" class="fa fa-edit fa-lg" style="color:orange;"></i> </a>

                            <form id="form-delete-{{$routing->id}}" action="{{route('routing.destroy',$routing->id)}}" style="display:none" method="POST">
                                @csrf
                                @method('DELETE')
                            </form>
                            <a href="#" onclick="
                                if(confirm('Yakin ingin menghapus?')){
                                    event.preventDefault();document.getElementById('form-delete-{{$routing->id}}').submit();
                                }else{
                                    event.preventDefault();
                                }
                                    " class="fa fa-trash fa-lg" style="color:red;"></i> </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div> <!-- /.table-stats -->
    </div>
</div>
@endsection

resources/views/admin/routing/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <strong class="card-title">Machine Show</strong>
            <a class="btn btn-warning float-right" href="{{route('plant.index')}}">Back</a>
        </div>

        <div class="card-body">

            <input type="text" name="machine" class="form-control" placeholder="Machine Name" value="{{$machine->name}}" readonly>
            <input type="text" name="tipe_kerusakan" class="form-control" placeholder="Jenis Kerusakan" value="{{$machine->damage_type}}" readonly>
            <input type="date" name="tanggal_masuk" class="form-control" placeholder="Tanggal Masuk" value="{{$machine->date_in}}" readonly>

            <a href="{{route('machine.index')}}" class="btn btn-warning">Kembali</a>
        </div>
    </div>
@endsection