routes/web.php
<?php

Route::get('/user', 'User\userController@index');



// route for admin
Route::namespace('Admin')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('index.home');
    });
    Route::get('/admin-home', 'AdminController@index')->name('admin.home');
    // pdc
    Route::resource('/admin/PDC', 'pdcController');
    Route::patch('/admin/PDC/dateout/update/{id}', 'pdcController@update_date_out')->name('PDC.date-out.update');
    Route::patch('/admin/PDC/progress_job/update/{id}', 'pdcController@update_progress_job')->name('PDC.progress-job.update');
    Route::patch('/admin/PDC/startprogress/update/{id}', 'pdcController@update_start_progress')->name('PDC.start-progress.update');
    Route::patch('/admin/PDC/done/update/{id}', 'pdcController@update_done')->name('PDC.done.update');


    // mkt
    Route::resource('/admin/MKT', 'mktController');
    Route::patch('/admin/MKT/dateout/update/{id}', 'mktController@update_date_out')->name('MKT.date-out.update');
    Route::patch('/admin/MKT/progress_job/update/{id}', 'mktController@update_progress_job')->name('MKT.progress-job.update');
    Route::patch('/admin/MKT/startprogress/update/{id}', 'mktController@update_start_progress')->name('MKT.start-progress.update');
    Route::patch('/admin/MKT/done/update/{id}', 'mktController@update_done')->name('MKT.done.update');

    // ppc
    Route::resource('/admin/PPC', 'disassyController');
    Route::patch('/admin/PPC/dateout/update/{id}', 'disassyController@update_date_out')->name('PPC.date-out.update');
    Route::patch('/admin/PPC/progress_job/update/{id}', 'disassyController@update_progress_job')->name('PPC.progress-job.update');
    Route::patch('/admin/PPC/startprogress/update/{id}', 'disassyController@update_start_progress')->name('PPC.start-progress.update');
    Route::patch('/admin/PPC/done/update/{id}', 'disassyController@update_done')->name('PPC.done.update');

    //machine
    Route::resource('/admin/machining', 'machineController');
    Route::patch('/admin/machining/startprogress/update/{id}', 'machineController@update_start_progress')->name('machining.start-progress.update');
    Route::patch('/admin/machining/endprogress/update/{id}', 'machineController@update_end_progress')->name('machining.end-progress.update');
    Route::patch('/admin/newmachine', 'machineController@new_machine')->name('machining.new-machine');
    Route::get('/admin/machining/done/{id}','machineController@done')->name('machining.done');
    Route::get('newmachine','machineController@machine_create')->name('machine.create');
    Route::post('machine/store','machineController@machine_store')->name('machine.store');

    //partkit
    Route::resource('/admin/partkit', 'partkitController');

    //partkit_po
    Route::get('/admin/partkit-po/create', 'partkitController@create_po')->name('partkit.create_po');
    Route::post('/admin/partkit-po/store', 'partkitController@store_po')->name('partkit.store_po');
    Route::patch('/admin/partkit-po/actrelease/update/{id}', 'partkitController@update_act_release_po')->name('partkit_po.update.act_release_po');
    Route::patch('/admin/partkit-po/ponumber/update/{id}', 'partkitController@update_po_number')->name('partkit_po.update.po_number');


    //assembly
    Route::resource('/admin/assembly', 'assemblyController');
    Route::patch('/admin/assembly-update/tube/{id}', 'assemblyController@update_tube')->name('assembly.update.tube');
    Route::patch('/admin/assembly-update/rod/{id}', 'assemblyController@update_rod')->name('assembly.update.rod');
    Route::patch('/admin/assembly-update/piston/{id}', 'assemblyController@update_piston')->name('assembly.update.piston');
    Route::patch('/admin/assembly-update/gland/{id}', 'assemblyController@update_gland')->name('assembly.update.gland');
    Route::patch('/admin/assembly-update/midle/{id}', 'assemblyController@update_midle')->name('assembly.update.midle');
    Route::patch('/admin/assembly-update/seal_kit/{id}', 'assemblyController@update_seal_kit')->name('assembly.update.seal_kit');
    Route::patch('/admin/assembly-update/bushing/{id}', 'assemblyController@update_bushing')->name('assembly.update.bushing');
    Route::patch('/admin/assembly-update/part_related/{id}', 'assemblyController@update_part_related')->name('assembly.update.part_related');

    // delay
    Route::resource('admin/delay', 'delayController');
    Route::patch('admin/delay/unpause/{id}', 'delayController@unpause')->name('machining.unpause');

    // routing
    Route::resource('/admin/routing', 'routingController');
    Route::post('/admin/routing/excel', 'routingController@excel')->name('routing.excel');
    Route::get('/admin/routing-edit/pdc', 'routingController@routing_pdc')->name('routing-edit.pdc');
    Route::post('/admin/routing-edit/pdc', 'routingController@routing_pdc_store')->name('routing-store.pdc');
    Route::delete('/admin/routing-edit/pdc/{id}', 'routingController@routing_pdc_delete')->name('relation_routing.destroy.pdc');
    Route::post('/admin/routing-edit/pdcstore', 'routingController@routing_pdc_store')->name('relation_routing.store.pdc');

    // routing ppc
    Route::get('/admin/routing-edit/ppc', 'routingController@routing_ppc')->name('routing-edit.ppc');
    Route::post('/admin/routing-edit/ppc', 'routingController@routing_ppc_store')->name('routing-store.ppc');
    Route::delete('/admin/routing-edit/ppc/{id}', 'routingController@routing_ppc_delete')->name('relation_routing.destroy.ppc');
    Route::post('/admin/routing-edit/ppcstore', 'routingController@routing_ppc_store')->name('relation_routing.store.ppc');

    //routing mkt
    Route::get('/admin/routing-edit/mkt', 'routingController@routing_mkt')->name('routing-edit.mkt');
    Route::post('/admin/routing-edit/mkt', 'routingController@routing_mkt_store')->name('routing-store.mkt');
    Route::delete('/admin/routing-edit/mkt/{id}', 'routingController@routing_mkt_delete')->name('relation_routing.destroy.mkt');
    Route::post('/admin/routing-edit/mktstore', 'routingController@routing_mkt_store')->name('relation_routing.store.mkt');

    // history
    Route::resource('/admin/history', 'historyController');

    // 
    Route::get('/pdc','userController@index')->name('user.pdc');
    Route::get('/station1', function () {
        return view('station1.home');
    });
});


Auth::routes();

app/Http/Controllers/API/mktController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Model\table_mkt;

class mktController extends Controller
{
    public function return_mkt(){
        return table_mkt::all();
    }
}

app/Http/Controllers/Admin/mktController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// use model
use App\Model\table_mkt;
use App\Model\routing;
use App\Model\std_leadtime;
use App\Model\Relation\relation_routings;


class mktController extends Controller
{
    public function index()
    {
        $mkts   = table_mkt::all();
        $routings  = routing::all();
        $std_leadtimes = std_leadtime::all();
        $relation_routings  = relation_routings::where('table_name', 'mkt')->get();

        return view('admin.mkt.index', compact('mkts', 'routings', 'relation_routings', 'std_leadtimes'));
    }

    public function create()
    {
        $routings  = routing::all();
        $relation_routings  = relation_routings::where('table_name', 'mkt')->get();
        return view('admin.mkt.create', compact('routings', 'relation_routings'));
    }

    public function store(Request $request)
    {

        $rules = [
            'register'              => 'required|',
            'unit_model'            => 'required',
            'nama_komponen'         => 'required',
            'date_in'               => 'required',
            'progress_job'          => 'required',

        ];

        $customMessages = [
            'required' => 'Kolom :attribute Harus diisi'
        ];

        $this->validate($request, $rules, $customMessages);
        $validatedData = $request->validate([]);

        $routing = routing::find($request->progress_job);
        $mkt = new table_mkt;

        $mkt->register              = $request->register;
        $mkt->unit_model            = $request->unit_model;
        $mkt->nama_komponen         = $request->nama_komponen;
        $mkt->date_in               = $request->date_in;
        $mkt->progress_job          = $routing->activity;
        $mkt->start_progress        = $request->start_progress;
        $mkt->date_out              = $request->date_out;
        $mkt->routing_id              = $routing->id;

        $mkt->save();

        return redirect(route('MKT.index'));
    }

    public function show($id)
    {

        $mkt = table_mkt::find($id)->routings();
        $mkt_routing = mkt_routing::where('table_mkt_id', $id)->orderBy('urutan')->get();
        $routings = routing::all();



        return view('admin.mkt.show', compact('mkt', 'mkt_routing', 'routings'));
    }

    public function edit($id)
    {
        $mkt = table_mkt::find($id);
        $routings = routing::all();

        return view('admin.mkt.edit', compact('mkt', 'routings'));
    }

    public function update(Request $request, $id)
    {

        $rules = [
            'register'              => 'required|',
            'unit_model'            => 'required',
            'nama_komponen'         => 'required',
            'date_in'               => 'required',
            'progress_job'          => 'required',

        ];

        $customMessages = [
            'required' => 'Kolom :attribute Harus diisi'
        ];

        $this->validate($request, $rules, $customMessages);
        $validatedData = $request->validate([]);

        $mkt =  table_mkt::find($id);

        $mkt->register              = $request->register;
        $mkt->unit_model            = $request->unit_model;
        $mkt->nama_komponen         = $request->nama_komponen;
        $mkt->date_in               = $request->date_in;
        $mkt->progress_job          = $request->progress_job;
        $mkt->start_progress        = $request->start_progress;
        $mkt->date_out              = $request->date_out;

        $mkt->update();

        return redirect(route('MKT.index'));
    }

    public function update_progress_job(Request $request, $id)
    {
        $data = table_mkt::find($id);
        $data->progress_job = $request->activity;
        $data->progress_job = $request->routing_id;
        $data->update();
        return redirect()->back();
    }

    public function update_date_out(Request $request, $id)
    {

        $data = table_mkt::find($id);
        $data->date_out = $request->date_out;
        $data->update();
        return redirect()->back();
    }

    public function update_start_progress(Request $request, $id)
    {
        $data = table_mkt::find($id);
        $data->start_progress = $request->start_progress;
        $data->update();
        return redirect()->back();
    }

    public function update_done(Request $request, $id)
    {
        $data = table_mkt::find($id);
        $data->done = 1;
        $data->laporan_keterlambatan = $request->laporan_keterlambatan;
        $data->update();
        return redirect()->back();
    }

    public function destroy($id)
    {
        $mkt = table_mkt::find($id);
        $mkt->delete();

        return redirect()->back();
    }
}

resources/views/admin/mkt/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Add New MKT</strong>
        <a class="btn btn-warning float-right" href="{{route('MKT.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        <form action="{{route('MKT.store')}}" method="POST">
            @csrf
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Register:</label>
                            <input type="text" name="register" class="form-control" placeholder="ex: BPC190001">
                        </div>
                        <div class="col-md-6">
                            <label>Unit Model</label>
                            <input type="text" name="unit_model" class="form-control" placeholder="ex: PC2000">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Nama Komponen</label>
                            <input type="text" name="nama_komponen" class="form-control" placeholder="ex: BUC">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Progress Job</label>
                            <select name="progress_job" class="form-control">
                                <option value="" selected disabled>Pilih</option>
                                @foreach($relation_routings as $relation_routing)
                                @foreach($routings as $routing)
                                @if($relation_routing->routing_id== $routing->id )
                                <option value="{{$routing->id}}">{{$routing->activity}}</option>
                                @endif
                                @endforeach
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-12">
                            <label>Date In</label>
                            <input type="date" name="date_in" class="form-control" placeholder="Date In">
                        </div>
                        {{-- <div class="col-md-6">
                            <label>Date Out</label>
                            <input type="date" name="date_out" class="form-control" placeholder="Date Out">
                        </div> --}}
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Start Progress</label>
                            <input type="datetime-local" name="start_progress" class="form-control"
                                placeholder="Start Progress">
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success form-control col-md-10">Tambah</button>
        </form>

    </div>
</div>
<datalist id="data-routing">
    @foreach($routings as $routing)
    <option value="{{$routing->id}}">{{$routing->activity}}</option>
    @endforeach
</datalist>
@endsection

resources/views/admin/mkt/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Edit MKT {{$mkt->register}}</strong>
        <a class="btn btn-warning float-right" href="{{route('MKT.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        <form action="{{route('MKT.update',$mkt->id)}}" method="POST">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Register:</label>
                            <input type="text" name="register" class="form-control" placeholder="ex: BPC190001"
                                value="{{$mkt->register}}">
                        </div>
                        <div class="col-md-6">
                            <label>Unit Model</label>
                            <input type="text" name="unit_model" class="form-control" placeholder="ex: PC2000"
                                value="{{$mkt->unit_model}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Nama Komponen</label>
                            <input type="text" name="nama_komponen" class="form-control" placeholder="ex: BUC"
                                value="{{$mkt->nama_komponen}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Progress Job</label>
                            <select name="progress_job" class="form-control">
                                <option value="" selected disabled>Pilih</option>
                                @foreach($routings as $routing)
                                <option value="{{$routing->activity}}" @if($mkt->progress_job == $routing->activity)
                                    selected @endif>{{$routing->activity}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Date In</label>
                            <input type="date" name="date_in" class="form-control" placeholder="Date In"
                                value="{{$mkt->date_in}}">
                        </div>
                        <div class="col-md-6">
                            <label>Date Out</label>
                            <input type="date" name="date_out" class="form-control" placeholder="Date Out"
                                value="{{$mkt->date_out}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Start Progress</label>
                            {{-- yang ini belum bisa ngasi value start progress daff --}}
                            <input type="datetime-local" name="start_progress" class="form-control"
                                placeholder="Start Progress">
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-warning form-control col-md-10">Update</button>
        </form>

    </div>
</div>
<datalist id="data-routing">
    @foreach($routings as $routing)
    <option value="{{$routing->id}}">{{$routing->activity}}</option>
    @endforeach
</datalist>
@endsection

resources/views/admin/mkt/routing-edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Edit Routing MKT</strong>
        <a class="btn btn-warning float-right" href="{{route('MKT.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')

        <div class="row mx-auto">

            <table class="table  col-md-6" id="dynamic_field">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Urutan Job</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody class="container1">

                    @foreach($routings as $routing)
                    @foreach($relation_routings as $relation_routing)
                    @if($routing->id == $relation_routing->routing_id)
                    <tr>
                        <td>{{$loop->index + 1}}</td>
                        <td><span>{{$routing->activity}}</span></td>
                        <form id="form-delete-{{$relation_routing->id}}"
                            action="{{route('relation_routing.destroy.pdc',$relation_routing->id)}}"
                            style="display:none" method="POST">
                            @csrf
                            @method('DELETE')
                        </form>
                        <td><a href="#" onclick="
                            if(confirm('Yakin ingin menghapus?')){
                                event.preventDefault();document.getElementById('form-delete-{{$relation_routing->id}}').submit();
                            }else{
                                event.preventDefault();
                            }
                                " class="fa fa-trash fa-lg" style="color:red;"></i> </a>
                        </td>
                    </tr>
                    @endif
                    @endforeach
                    @endforeach

                    {{-- <form action="{{route('relation_routing.store.pdc')}}" method="POST">
                    @csrf
                    <tr>
                        <td>#</td>
                        <td>
                            <input type="text" name="routing_pdc" list="data-routing">
                        </td>
                        <td><button type="submit">tambah</button></td>
                    </tr>
                    </form> --}}
                </tbody>
            </table>
        </div><br><br>
        <hr>
        <form action="{{route('relation_routing.store.mkt')}}" method="POST">
            @csrf
        <div class="row">
            <div class="col-md-3">
                <label>Unit Model</label>
                <select name="unit_model" id="unit_model" class="form-control">
                    <option value="" disabled selected>Pilih..</option>
                    @php
                    $model_units = $routings->unique('model_unit'); $model_units->values()->all();
                    @endphp
                    @foreach($model_units as $model_unit)
                    <option value="{{$model_unit->model_unit}}">{{$model_unit->model_unit}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-3">
                <label>Komponen</label>
                <select name="komponen" id="komponen" class="form-control" disabled>
                    <option value="" disabled selected>Pilih..</option>
                    @php
                    $komponens = $routings->unique('komponen'); $komponens->values()->all();
                    @endphp
                    @foreach($komponens as $komponen)
                    <option value="{{$komponen->komponen}}" class="{{$komponen->model_unit}}">
                        {{$komponen->komponen}}</option>
                    {{-- <option value="Boom" class="pc1000">Boom</option>
                                <option value="BUC" class="pc2000">Bucket</option> --}}
                    @endforeach
                </select>
                <script>
                    $("#unit_model").change(function () {
                        $('#komponen').removeAttr('disabled');
                        if ($(this).val() == "PC2000") {
                            $(".HD785-7").hide();
                            $(".PC2000").show();
                        } else if ($(this).val() == "PC1250") {
                            $(".HD785-7").hide();
                            $(".PC2000").show();
                        } else if ($(this).val() == "PC750/PC800") {
                            $(".HD785-7").hide();
                            $(".PC2000").show();
                        } else {
                            $(".PC2000").hide();
                            $(".HD785-7").show();
                        }
                    });

                </script>
            </div>
        </div><br>
        <div class="row">
            <div class="col-md-3">
                <label>Sub Komponen</label>
                <select name="sub_komponen" id="sub_komponen" class="form-control" disabled>
                    <option value="" disabled selected>Pilih..</option>
                    @php
                    $sub_komponens = $routings->unique('sub_komponen'); $sub_komponens->values()->all();
                    @endphp
                    @foreach($sub_komponens as $sub_komponen)
                    <option value="{{$sub_komponen->sub_komponen}}" class="sub_{{$komponen->model_unit}}">
                        {{$sub_komponen->sub_komponen}}</option>
                    {{-- <option value="Boom" class="pc1000">Boom</option>
                                <option value="BUC" class="pc2000">Bucket</option> --}}
                    @endforeach
                </select>
                <script>
                    $("#komponen").change(function () {
                        $('#sub_komponen').removeAttr('disabled');
                        if ($(this).val() == "Rod") {
                            $(".HD785-7").hide();
                            $(".PC2000").show();
                        }
                    });

                </script>
            </div>
            <div class="col-md-3">
                <label>Tipe Kerusakan</label>
                <select name="kategori_kerusakan" id="tipe_kerusakan" class="form-control" disabled>
                    <option value="" disabled selected>Pilih..</option>
                    @php
                    $tipe_kerusakans = $routings->unique('kategori_kerusakan');
                    $tipe_kerusakans->values()->all();
                    @endphp
                    @foreach($tipe_kerusakans as $tipe_kerusakan)
                    <option value="{{$tipe_kerusakan->kategori_kerusakan}}">
                        {{$tipe_kerusakan->kategori_kerusakan}}</option>
                    @endforeach
                </select>
                <script>
                    var komponen = $("#komponen").val();
                    var subKomponen = $("#sub_komponen").val();
                    $("#sub_komponen").change(function () {
                        $('#tipe_kerusakan').removeAttr('disabled');
                    });

                </script>
            </div>
        </div><br>
        <div class="row col-md-6">
            <div class="col-md-12 ">
                <label>Progress Job</label>
                <select name="progress_job" class="form-control" id="progress_job" disabled>
                    <option value="" selected disabled>Pilih</option>
                    @php
                    $activities = $routings->unique('activity'); $activities->values()->all();
                    @endphp
                    @foreach ($activities as $activity)
                    <option value="{{$activity->activity}}" class="activity_job"
                        sub-komponen="{{$activity->sub_komponen}}"
                        kategori-kerusakan="{{$activity->kategori_kerusakan}}">{{$activity->activity}}
                    </option>
                    @endforeach
                </select>
                <script>
                    $("#sub_komponen").change(function () {
                        $('#progress_job').attr('disabled', 'disabled');
                    });
                    $("#tipe_kerusakan").change(function () {
                        var sub_komponen = $('#sub_komponen').val();
                        var kerusakan = $('#tipe_kerusakan').val();
                        $('#progress_job').removeAttr('disabled');
                        $('.activity_job').hide();
                        $('.activity_job[sub-komponen*=' + sub_komponen + '][kategori-kerusakan*=' + kerusakan +
                            ']').show();
                    });

                </script>
            </div>
            <button type="submit" href="#" class="btn btn-success col-md-6 mx-auto" style="margin:10px">Tambah</button>
        </div>
    </form>
    </div>
    <br>
</div>
<datalist id="data-routing">
    @foreach($routings as $routing)
    <option value="{{$routing->id}}">{{$routing->activity}}</option>
    @endforeach
</datalist>
<script>
    $(document).ready(function () {
        var max_fields = 10;
        var wrapper = $(".container1");
        var add_button = $(".add_form_field");
        var x = 1;
        $(add_button).click(function (e) {
            e.preventDefault();
            if (x < max_fields) {
                x++;
                $(wrapper).append(
                    '<tr id="row' + x + '"><td> ' + x +
                    ' </td><td><input class="form-control" name="routings[]" id="answer" list="data-routing"><input name="urutan[]"  type="hidden" value="' +
                    x + '"></td><td><a href="#" class="delete btn btn-danger">Delete</a></td></tr>');
            } else {
                alert('You Reached the limits')
            }
        });

        $(wrapper).on("click", ".delete", function (e) {
            e.preventDefault();
            $('#row' + x + '').remove();
            x--;
        })
    });

</script>
@endsection

resources/views/admin/mkt/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <strong class="card-title">Machine Show</strong>
            <a class="btn btn-warning float-right" href="{{route('plant.index')}}">Back</a>
        </div>

        <div class="card-body">

            <input type="text" name="machine" class="form-control" placeholder="Machine Name" value="{{$machine->name}}" readonly>
            <input type="text" name="tipe_kerusakan" class="form-control" placeholder="Jenis Kerusakan" value="{{$machine->damage_type}}" readonly>
            <input type="date" name="tanggal_masuk" class="form-control" placeholder="Tanggal Masuk" value="{{$machine->date_in}}" readonly>

            <a href="{{route('machine.index')}}" class="btn btn-warning">Kembali</a>
        </div>
    </div>
@endsection