routes/web.php
<?php

Route::get('/user', 'User\userController@index');



// route for admin
Route::namespace('Admin')->middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('index.home');
    });
    Route::get('/admin-home', 'AdminController@index')->name('admin.home');
    // pdc
    Route::resource('/admin/PDC', 'pdcController');
    Route::patch('/admin/PDC/dateout/update/{id}', 'pdcController@update_date_out')->name('PDC.date-out.update');
    Route::patch('/admin/PDC/progress_job/update/{id}', 'pdcController@update_progress_job')->name('PDC.progress-job.update');
    Route::patch('/admin/PDC/startprogress/update/{id}', 'pdcController@update_start_progress')->name('PDC.start-progress.update');
    Route::patch('/admin/PDC/done/update/{id}', 'pdcController@update_done')->name('PDC.done.update');


    // mkt
    Route::resource('/admin/MKT', 'mktController');
    Route::patch('/admin/MKT/dateout/update/{id}', 'mktController@update_date_out')->name('MKT.date-out.update');
    Route::patch('/admin/MKT/progress_job/update/{id}', 'mktController@update_progress_job')->name('MKT.progress-job.update');
    Route::patch('/admin/MKT/startprogress/update/{id}', 'mktController@update_start_progress')->name('MKT.start-progress.update');
    Route::patch('/admin/MKT/done/update/{id}', 'mktController@update_done')->name('MKT.done.update');

    // ppc
    Route::resource('/admin/PPC', 'disassyController');
    Route::patch('/admin/PPC/dateout/update/{id}', 'disassyController@update_date_out')->name('PPC.date-out.update');
    Route::patch('/admin/PPC/progress_job/update/{id}', 'disassyController@update_progress_job')->name('PPC.progress-job.update');
    Route::patch('/admin/PPC/startprogress/update/{id}', 'disassyController@update_start_progress')->name('PPC.start-progress.update');
    Route::patch('/admin/PPC/done/update/{id}', 'disassyController@update_done')->name('PPC.done.update');

    //machine
    Route::resource('/admin/machining', 'machineController');
    Route::patch('/admin/machining/startprogress/update/{id}', 'machineController@update_start_progress')->name('machining.start-progress.update');
    Route::patch('/admin/machining/endprogress/update/{id}', 'machineController@update_end_progress')->name('machining.end-progress.update');
    Route::patch('/admin/newmachine', 'machineController@new_machine')->name('machining.new-machine');
    Route::get('/admin/machining/done/{id}','machineController@done')->name('machining.done');
    Route::get('newmachine','machineController@machine_create')->name('machine.create');
    Route::post('machine/store','machineController@machine_store')->name('machine.store');

    //partkit
    Route::resource('/admin/partkit', 'partkitController');

    //partkit_po
    Route::get('/admin/partkit-po/create', 'partkitController@create_po')->name('partkit.create_po');
    Route::post('/admin/partkit-po/store', 'partkitController@store_po')->name('partkit.store_po');
    Route::patch('/admin/partkit-po/actrelease/update/{id}', 'partkitController@update_act_release_po')->name('partkit_po.update.act_release_po');
    Route::patch('/admin/partkit-po/ponumber/update/{id}', 'partkitController@update_po_number')->name('partkit_po.update.po_number');


    //assembly
    Route::resource('/admin/assembly', 'assemblyController');
    Route::patch('/admin/assembly-update/tube/{id}', 'assemblyController@update_tube')->name('assembly.update.tube');
    Route::patch('/admin/assembly-update/rod/{id}', 'assemblyController@update_rod')->name('assembly.update.rod');
    Route::patch('/admin/assembly-update/piston/{id}', 'assemblyController@update_piston')->name('assembly.update.piston');
    Route::patch('/admin/assembly-update/gland/{id}', 'assemblyController@update_gland')->name('assembly.update.gland');
    Route::patch('/admin/assembly-update/midle/{id}', 'assemblyController@update_midle')->name('assembly.update.midle');
    Route::patch('/admin/assembly-update/seal_kit/{id}', 'assemblyController@update_seal_kit')->name('assembly.update.seal_kit');
    Route::patch('/admin/assembly-update/bushing/{id}', 'assemblyController@update_bushing')->name('assembly.update.bushing');
    Route::patch('/admin/assembly-update/part_related/{id}', 'assemblyController@update_part_related')->name('assembly.update.part_related');

    // delay
    Route::resource('admin/delay', 'delayController');
    Route::patch('admin/delay/unpause/{id}', 'delayController@unpause')->name('machining.unpause');

    // routing
    Route::resource('/admin/routing', 'routingController');
    Route::post('/admin/routing/excel', 'routingController@excel')->name('routing.excel');
    Route::get('/admin/routing-edit/pdc', 'routingController@routing_pdc')->name('routing-edit.pdc');
    Route::post('/admin/routing-edit/pdc', 'routingController@routing_pdc_store')->name('routing-store.pdc');
    Route::delete('/admin/routing-edit/pdc/{id}', 'routingController@routing_pdc_delete')->name('relation_routing.destroy.pdc');
    Route::post('/admin/routing-edit/pdcstore', 'routingController@routing_pdc_store')->name('relation_routing.store.pdc');

    // routing ppc
    Route::get('/admin/routing-edit/ppc', 'routingController@routing_ppc')->name('routing-edit.ppc');
    Route::post('/admin/routing-edit/ppc', 'routingController@routing_ppc_store')->name('routing-store.ppc');
    Route::delete('/admin/routing-edit/ppc/{id}', 'routingController@routing_ppc_delete')->name('relation_routing.destroy.ppc');
    Route::post('/admin/routing-edit/ppcstore', 'routingController@routing_ppc_store')->name('relation_routing.store.ppc');

    //routing mkt
    Route::get('/admin/routing-edit/mkt', 'routingController@routing_mkt')->name('routing-edit.mkt');
    Route::post('/admin/routing-edit/mkt', 'routingController@routing_mkt_store')->name('routing-store.mkt');
    Route::delete('/admin/routing-edit/mkt/{id}', 'routingController@routing_mkt_delete')->name('relation_routing.destroy.mkt');
    Route::post('/admin/routing-edit/mktstore', 'routingController@routing_mkt_store')->name('relation_routing.store.mkt');

    // history
    Route::resource('/admin/history', 'historyController');

    // 
    Route::get('/pdc','userController@index')->name('user.pdc');
    Route::get('/station1', function () {
        return view('station1.home');
    });
});


Auth::routes();

app/Http/Controllers/Admin/partkitController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\table_partkit_satu;
use App\Model\table_partkit;
use App\Model\routing;
use Carbon\Carbon;

class partkitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $partkit_satus  = table_partkit_satu::all();
        $partkits        = table_partkit::all();
        $routings       = routing::all();
        return view('admin.partkit.index', compact('partkit_satus','partkits','routings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.partkit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    // PO PARTKIT

    public function create_po()
    {
        return view('admin.partkit.create_po');
    }

    public function store_po(Request $request)
    {

        $rules = [
            'register'              => 'required|',
            'unit_model'            => 'required',
            'nama_komponen'         => 'required',
            'std_release_po'        => 'required',
            'pro_number'            => 'required',

        ];

        $customMessages = [
            'required' => 'Kolom :attribute Harus diisi'
        ];

        $this->validate($request, $rules, $customMessages);
        $validatedData = $request->validate([]);

        $partkit_satus = new table_partkit_satu;

        $partkit_satus->register              = $request->register;
        $partkit_satus->pro_number            = $request->pro_number;
        $partkit_satus->unit_model            = $request->unit_model;
        $partkit_satus->nama_komponen         = $request->nama_komponen;
        $partkit_satus->req_iserve            = $request->req_iserve;
        $partkit_satus->po_number             = $request->po_number;
        $partkit_satus->std_release_po        = $request->std_release_po;
        $partkit_satus->drawing_engineer      = $request->drawing_engineer;
        $partkit_satus->status_drawing        = $request->status_drawing;

        $partkit_satus->save();

        return redirect(route('partkit.index'));
    }
    public function update_act_release_po(Request $request, $id)
    {
        $data = table_partkit_satu::find($id);
        $data->act_release_po = $request->act_release_po;
        $data->update();
        return redirect()->back();
    }
    public function update_po_number(Request $request, $id)
    {
        $data = table_partkit_satu::find($id);
        $data->po_number = $request->po_number;
        $data->update();
        return redirect()->back();
    }
}

resources/views/admin/partkit/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Add New PartKit</strong>
        <a class="btn btn-warning float-right" href="{{route('partkit.index')}}">Back</a>
    </div>

    <div class="card-body">
        
    </div>
</div>
@endsection

resources/views/admin/partkit/create_po.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Add New PartKit PO</strong>
        <a class="btn btn-warning float-right" href="{{route('partkit.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        <form action="{{route('partkit.store_po')}}" method="POST">
            @csrf
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Register:</label>
                            <input type="text" name="register" class="form-control" placeholder="ex: BPC190001">
                        </div>
                        <div class="col-md-6">
                            <label>Unit Model</label>
                            <input type="text" name="unit_model" class="form-control" placeholder="ex: PC2000">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-5">
                            <label>Nama Komponen</label>
                            <input type="text" name="nama_komponen" class="form-control" placeholder="ex: BUC">
                        </div>
                        <div class="col-md-7">
                            <label>Std Release PO (Hari)</label>
                            <div class="input-group mb-3">
                                <input type="number" name="std_release_po" class="form-control" placeholder="ex: 1"
                                    aria-label="std-release-po" aria-describedby="std-release">
                                <div class="input-group-append">
                                    <span class="input-group-text" id="std-release">Hari</span>
                                </div>
                            </div>
                            <label class="text-danger">*Std Release default = 1</label>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Req Iserve</label>
                            <input type="date" name="req_iserve" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label>PO Number</label>
                            <input type="text" class="form-control" name="po_number" placeholder="ex: 92000xxx">
                        </div>
                        <div class="col-md-12" style="text-align:center;">
                            <label class="text-danger">*Jika belum ada, kosongkan data diatas</label>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-12">
                            <label>Pro Number</label>
                            <input type="text" name="pro_number" class="form-control" placeholder="ex: 66729xx">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label style="margin-left:170px;">Status Drawing</label>
                            <br>
                            <div class="table-stats order-table ov-h" style="margin-left:50px;">
                                <table style="text-align:center; width:100%;">
                                    <thead>
                                        <tr>
                                            <th rowspan="2">List</th>
                                            <th colspan="2" style="padding-right:70px">Status</th>
                                        </tr>
                                        <tr>
                                            <th style="padding-left:50px">Ok</th>
                                            <th style="padding-right:40px">Not</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Drawing Engineer</td>
                                            <td style="padding-left:50px">
                                                <input type="radio" name="drawing_engineer" value="OK">
                                            </td>
                                            <td style="padding-right:50px">
                                                <input type="radio" name="drawing_engineer" value="Not" checked>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Status Drawing</td>
                                            <td style="padding-left:50px">
                                                <input type="radio" name="status_drawing" value="Finish">
                                            </td>
                                            <td style="padding-right:50px">
                                                <input type="radio" name="status_drawing" value="Not" checked>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <br>
                                <label class="text-danger">*Select pada lingkaran untuk menambahkan status</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success form-control col-md-10">Tambah</button>
        </form>

    </div>
</div>
@endsection

resources/views/admin/partkit/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Edit PDC {{$pdc->register}}</strong>
        <a class="btn btn-warning float-right" href="{{route('PDC.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        <form action="{{route('PDC.update',$pdc->id)}}" method="POST">
            @csrf
            @method('PATCH')
            <div class="row">
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Register:</label>
                            <input type="text" name="register" class="form-control" placeholder="ex: BPC190001" value="{{$pdc->register}}">
                        </div>
                        <div class="col-md-6">
                            <label>Unit Model</label>
                            <input type="text" name="unit_model" class="form-control" placeholder="ex: PC2000" value="{{$pdc->unit_model}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Nama Komponen</label>
                            <input type="text" name="nama_komponen" class="form-control" placeholder="ex: BUC" value="{{$pdc->nama_komponen}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Progress Job</label>
                            <select name="progress_job" class="form-control">
                                <option value="" selected disabled>Pilih</option>
                            @foreach($routings as $routing)
                                <option value="{{$routing->activity}}" @if($pdc->progress_job == $routing->activity) selected @endif>{{$routing->activity}}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Date In</label>
                            <input type="date" name="date_in" class="form-control" placeholder="Date In" value="{{$pdc->date_in}}">
                        </div>
                        <div class="col-md-6">
                            <label>Date Out</label>
                            <input type="date" name="date_out" class="form-control" placeholder="Date Out" value="{{$pdc->date_out}}">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <label>Start Progress</label>
                            {{-- yang ini belum bisa ngasi value start progress daff --}}
                            <input type="datetime-local" name="start_progress" class="form-control" placeholder="Start Progress" >
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-warning form-control col-md-10">Update</button>
        </form>

    </div>
</div>
<datalist id="data-routing">
    @foreach($routings as $routing)
    <option value="{{$routing->id}}">{{$routing->activity}}</option>
    @endforeach
</datalist>
@endsection

resources/views/admin/partkit/routing-edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <strong class="card-title">Edit Routing PDC</strong>
        <a class="btn btn-warning float-right" href="{{route('PDC.index')}}">Back</a>
    </div>

    <div class="card-body">
        @include('includes.error')
        
            <div class="row mx-auto">

                <table class="table  col-md-6" id="dynamic_field">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Urutan Job</th>
                            <th scope="col">Aksi</th>
                        </tr>
                    </thead>
                    <tbody class="container1">
                        
                        @foreach($routings as $routing)
                            @foreach($relation_routings as $relation_routing)
                                @if($routing->id == $relation_routing->routing_id)
                                    <tr>
                                        <td>{{$loop->index + 1}}</td>
                                        <td><span>{{$routing->activity}}</span></td>
                                        <form id="form-delete-{{$relation_routing->id}}" action="{{route('relation_routing.destroy.pdc',$relation_routing->id)}}" style="display:none" method="POST">
                                            @csrf
                                            @method('DELETE')
                                        </form>
                                        <td><a href="#" onclick="
                                            if(confirm('Yakin ingin menghapus?')){
                                                event.preventDefault();document.getElementById('form-delete-{{$relation_routing->id}}').submit();
                                            }else{
                                                event.preventDefault();
                                            }
                                                " class="fa fa-trash fa-lg" style="color:red;"></i> </a>
                                        </td>
                                    </tr>
                                @endif
                            @endforeach
                        @endforeach
                        
                        <form action="{{route('relation_routing.store.pdc')}}" method="POST">
                            @csrf 
                            <tr>
                                <td>#</td>
                                <td>
                                    <input type="text" name="routing_pdc" list="data-routing">
                                </td>
                                <td><button type="submit">tambah</button></td>
                            </tr>
                        </form>
                    </tbody>
                </table>
            </div>


    </div>
</div>
<datalist id="data-routing">
    @foreach($routings as $routing)
    <option value="{{$routing->id}}">{{$routing->activity}}</option>
    @endforeach
</datalist>
<script>
    $(document).ready(function () {
        var max_fields = 10;
        var wrapper = $(".container1");
        var add_button = $(".add_form_field");
        var x = 1;
        $(add_button).click(function (e) {
            e.preventDefault();
            if (x < max_fields) {
                x++;
                $(wrapper).append(
                    '<tr id="row'+x+'"><td> ' + x + ' </td><td><input class="form-control" name="routings[]" id="answer" list="data-routing"><input name="urutan[]"  type="hidden" value="'+ x +'"></td><td><a href="#" class="delete btn btn-danger">Delete</a></td></tr>');
            } else {
                alert('You Reached the limits')
            }
        });

        $(wrapper).on("click", ".delete", function (e) {
            e.preventDefault();
            $('#row'+x+'').remove();
            x--;
        })
    });

</script>
@endsection

resources/views/admin/partkit/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <strong class="card-title">PDC Show</strong>
            <a class="btn btn-warning float-right" href="{{route('PDC.index')}}">Back</a>
        </div>

        <div class="card-body">
                    <div class="row mx-auto">
        
                        <table class="table  col-md-6" id="dynamic_field">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Urutan Job</th>
                                    <th scope="col">Routing</th>
                                </tr>
                            </thead>
                            <tbody class="container1">
                                @foreach($pdc->routings as $pdcrouting)
                                <tr>
                                    <td >{{$loop->index + 1}}</td>
                                    <td class="id-routing">{{$pdcrouting->activity}}</td>
                                    <td><span class="estimasi-routing" id="estimasi-id-{{$loop->index + 1}}">{{$pdcrouting->estimasi}}</span></td>
                                </tr>
                                @endforeach
                                
                            </tbody>
                        </table>
                    </div>
           
                    <div class="table-stats order-table ov-h">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>register</th>
                                        <th>unit model</th>
                                        <th>nama komponen</th>
                                        <th>date in</th>
                                        <th>progress job</th>
                                        <th>routing</th>
                                        <th>start progress</th>
                                        <th>date out</th>
                                        <th>lead time</th>
                                        <th>std leadtime</th>
                                        <th>status leadtime</th>
                                        <th>plan ready go ahead</th>
                                        <TH>Real Time</TH>
                                        <th>%tage progress</th>
            
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                        
                                    <tr>
                                        <td class="serial">{{$pdc->id}}</td>
                                        <td>{{$pdc->register}}</td>
                                        <td>{{$pdc->unit_model}}</td>
                                        <td>{{$pdc->nama_komponen}}</td>
                                        <td>{{$pdc->date_in}}</td>
                                        <td>{{$pdc->progress_job}}</td>
                                        <td id="sisa"></td>
                                        <td>{{$pdc->start_progress}}</td>
                                        <td>{{$pdc->date_out}}</td>
                                        <td>{{$pdc->leadtime}}</td>
                                        <td>{{$pdc->std_leadtime_id}}</td>
                                        <td>{{$pdc->status_leadtime}}</td>
                                        <td>{{$pdc->plan_ready_go_ahead}}</td>
                                        <td id="the-final-countdown"></td>
                                        <td  style="display:none" class="routing-tampil"> {{$pdc->progress_job}}</td>
                                        <td>{{$pdc->percentage_progress}}</td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
            </div>
    </div>
    
    <script>
        $( document ).ready(function() {
            var elemen = document.getElementsByClassName('id-routing');
            var elemen_tampil = document.getElementsByClassName('routing-tampil');



            var arr = jQuery.makeArray(elemen);
            var arr_tampil = jQuery.makeArray(elemen_tampil);
            var arrL = arr.length;
            var arr_tampilL = arr_tampil.length;
                
            for(i=0;i<arrL;i++){
                routing = $(arr[i]).text();
                for(x=0;x<arr_tampilL;x++){
                    hasilRouting= $(arr_tampil[i]).text();
                    if(routing=hasilRouting){
                        a= x+1;
                        datatampil= document.getElementById('estimasi-id-' + a);
                        // console.log($(datatampil).text());
                    }
                }
                
            }

            // $(arr).each(function() {
            //     console.log(Object.keys(arr));
            //     var arrData = $(this).text();
            //     $(arr_tampil).each(function() {
            //         arrTampil= $(this).text();
            //         if(arrTampil = arrData){
                        
            //             // var hasilAkhir = document.getElementById('estimasi-id-').text();
            //             // console.log(Object.keys(arrTampil));
            //         }
            //     });
            // });
        });

        var waktu = 4*60*60;
        
            setInterval(function time(){
                var d = new Date();
                var hours = 24 - d.getHours();
                var min = 60 - d.getMinutes();
                if((min + '').length == 1){
                    min = '0' + min;
                }
                var sec = 60 - d.getSeconds();
                if((sec + '').length == 1){
                        sec = '0' + sec;
                }
                jQuery('#the-final-countdown').html(hours+':'+min+':'+sec)
                }, 1000);
    </script>
    
@endsection